spring:
  main:
    banner-mode: "off"
  application:
    name: heroku-blog
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
server:
  # 启用GZIP压缩
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/xml,application/xhtml+xml,text/css,application/javascript,application/x-javascript,image/svg+xml
  port: 9000
  servlet:
    session:
      cookie:
        name: LZQWEBSOFT_SESSIONID
        http-only: true
        secure: false
  # 禁用系统错误处理，开启自定义错误控制器
  error:
    whitelabel:
      enabled: false
logging:
  path: /var/log/
  file: heroku-blog-info.log
  level:
    root: info
    org.hibernate: WARN

