spring:
  main:
    banner-mode: "off"
  application:
    name: heroku-blog
server:
  # 启用GZIP压缩
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/xml,application/xhtml+xml,text/css,application/javascript,application/x-javascript,image/svg+xml
  port: 9001
  servlet:
    session:
      cookie:
        name: LZQWEBSOFT_SESSIONID
        http-only: true
        secure: false
logging:
  path: /var/log/
  file: heroku-blog-info.log
  level:
    root: info
    org.hibernate: WARN

